// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RemindMe.Data;

namespace RemindMe.Data.Migrations
{
    [DbContext(typeof(RemindMeDatabaseContext))]
    partial class RemindMeDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RemindMe.Models.RemindMeUser", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("MostRecentLogin");

                    b.Property<Guid>("UserGuid");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("RemindMeUsers");
                });

            modelBuilder.Entity("RemindMe.Models.Reminder", b =>
                {
                    b.Property<long>("ReminderId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("CronExpression");

                    b.Property<string>("Description");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<DateTime>("LastRunDate");

                    b.Property<string>("Name");

                    b.Property<string>("RecipientEmailAddress");

                    b.Property<string>("RecipientPhoneNumber");

                    b.Property<long>("UserIdFk");

                    b.HasKey("ReminderId");

                    b.ToTable("Reminders");
                });
#pragma warning restore 612, 618
        }
    }
}
