// <auto-generated />
using System;
using Log4Npg.Logging.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Log4Npg.Logging.Migrations
{
    [DbContext(typeof(LoggingDatabaseContext))]
    [Migration("20190901061928_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Log4Npg.Models.LogEntry", b =>
                {
                    b.Property<long>("LogEntryId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("EventTime");

                    b.Property<int>("Level");

                    b.Property<string>("Message")
                        .HasColumnType("jsonb");

                    b.HasKey("LogEntryId");

                    b.ToTable("LogEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
